CREATE SEQUENCE TYRE_MANUFACTURER_SEQ;

CREATE TABLE TYRE_MANUFACTURER (
	MANUFACTURER_ID INT NOT NULL,
	MANUFACTURER_NAME VARCHAR(100),
	DESCRIPTION VARCHAR(2000),
	PRIMARY KEY (MANUFACTURER_ID)
);

CREATE SEQUENCE TYRE_BRAND_SEQ;

CREATE TABLE TYRE_BRAND (
	BRAND_ID INT NOT NULL,
	MANUFACTURER_ID INT,
	BRAND_NAME VARCHAR(100),
	MILEAGE NUMERIC,
	THRESHOLD NUMERIC,
	PRIMARY KEY (BRAND_ID),
	FOREIGN KEY (MANUFACTURER_ID) REFERENCES TYRE_MANUFACTURER(MANUFACTURER_ID)
);

CREATE SEQUENCE BUS_PROVIDER_SEQ;

CREATE TABLE BUS_PROVIDER (
	PROVIDER_ID INT NOT NULL,
	PROVIDER_NAME VARCHAR(100),
	DESCRIPTION VARCHAR(2000),
	PRIMARY KEY (PROVIDER_ID)
);

CREATE SEQUENCE BUS_INVENTORY_SEQ;

CREATE TABLE BUS_INVENTORY (
	BUS_ID INT NOT NULL,
	PROVIDER_ID INT,
	NAME VARCHAR(100),
	PRIMARY KEY (BUS_ID),
	FOREIGN KEY (PROVIDER_ID) REFERENCES BUS_PROVIDER(PROVIDER_ID)
);

CREATE SEQUENCE TYRE_INVENTORY_SEQ;

CREATE TABLE TYRE_INVENTORY (
	TYRE_ID INT NOT NULL,
	BRAND_ID INT,
	BUS_ID INT,
	DISTANCE_TRAVELLED NUMERIC,
	THRESHOLD_FLAG VARCHAR(1),
	COST NUMERIC,
	PURCHASE_DATE TIMESTAMP,
	PRIMARY KEY (TYRE_ID),
	FOREIGN KEY (BRAND_ID) REFERENCES TYRE_BRAND(BRAND_ID),
	FOREIGN KEY (BUS_ID) REFERENCES BUS_INVENTORY(BUS_ID)
);

CREATE SEQUENCE TRIP_SEQ;

CREATE TABLE TRIP (
	TRIP_ID INT NOT NULL,
	BUS_ID INT,
	ORIGIN VARCHAR(100),
	DESTINATION VARCHAR(100),
	DISTANCE NUMERIC,
	TRIP_DATE TIMESTAMP,
	FOREIGN KEY (BUS_ID) REFERENCES BUS_INVENTORY(BUS_ID)
);

CREATE SEQUENCE PURCHASE_ORDER_SEQ;

CREATE TABLE PURCHASE_ORDER (
	ID INT NOT NULL,
	BRAND_ID INT,
	QUANTITY NUMERIC,
	ORDER_DATE TIMESTAMP,
	PRICE NUMERIC,
	FOREIGN KEY (BRAND_ID) REFERENCES TYRE_BRAND(BRAND_ID)
);


