INSERT INTO BUS_INVENTORY VALUES (NEXTVAL('BUS_INVENTORY_SEQ'), 1, 'GH-1002');
INSERT INTO BUS_INVENTORY VALUES (NEXTVAL('BUS_INVENTORY_SEQ'), 2, 'SH-1002');
INSERT INTO BUS_INVENTORY VALUES (NEXTVAL('BUS_INVENTORY_SEQ'), 3, 'NE-1001');
INSERT INTO BUS_INVENTORY VALUES (NEXTVAL('BUS_INVENTORY_SEQ'), 3, 'NE-1002');
INSERT INTO BUS_INVENTORY VALUES (NEXTVAL('BUS_INVENTORY_SEQ'), 4, 'MA-1001');
INSERT INTO BUS_INVENTORY VALUES (NEXTVAL('BUS_INVENTORY_SEQ'), 4, 'MA-1002');
INSERT INTO BUS_INVENTORY VALUES (NEXTVAL('BUS_INVENTORY_SEQ'), 5, 'BO-1001');
INSERT INTO BUS_INVENTORY VALUES (NEXTVAL('BUS_INVENTORY_SEQ'), 6, 'RE-1001');