INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 1, 3, 0, 'N', 200, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 1, 3, 0, 'N', 200, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 1, 3, 0, 'N', 200, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 1, 3, 0, 'N', 200, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 2, 4, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 2, 4, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 3, 4, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 3, 4, 0, 'N', 300, now());