INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 1, 3, 0, 'N', 200, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 1, 3, 0, 'N', 200, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 1, 3, 0, 'N', 200, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 1, 3, 0, 'N', 200, now());

INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 2, 4, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 2, 4, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 3, 4, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 3, 4, 0, 'N', 300, now());

INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 4, 5, 0, 'N', 200, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 5, 5, 0, 'N', 200, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 6, 5, 0, 'N', 200, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 7, 5, 0, 'N', 200, now());

INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 8, 6, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 8, 6, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 5, 6, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 6, 6, 0, 'N', 300, now());

INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 8, 7, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 7, 7, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 6, 7, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 5, 7, 0, 'N', 300, now());

INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 7, 8, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 7, 8, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 7, 8, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 7, 8, 0, 'N', 300, now());

INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 6, 9, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 5, 9, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 5, 9, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 5, 9, 0, 'N', 300, now());

INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 6, 10, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 6, 10, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 7, 10, 0, 'N', 300, now());
INSERT INTO TYRE_INVENTORY VALUES (NEXTVAL('TYRE_INVENTORY_SEQ'), 7, 10, 0, 'N', 300, now());